version: '2'
services:
  app:
    build: .
    working_dir: /app
    volumes:
      - ./config:/app/config
      - ./public:/app/public
      - ./scripts:/app/scripts
      - ./src:/app/src
    ports:
      - '3000:3000'
    command: 'npm start'
